### ISSUE TITLE
Dataloader returned 0 length

### ISSUE THREAD

**Issue by xjiangfan** [yichen928/STRL#4]
Sorry to bother you, I've got an error when running train.py. ShapeNet is used as a pre-training dataset and ModelNet40 is an evaluation dataset. The two datasets are downloaded and I put them in a directory as described readme file. The detail of traceback information as follows.

Traceback (most recent call last):
  File "/home/jiangfan/workspace/codespace/STRL/BYOL/train.py", line 67, in <module>
    main()
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/hydra/main.py", line 20, in decorated_main
    run_hydra(
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 171, in run_hydra
    hydra.run(
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 82, in run
    return run_job(
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jiangfan/workspace/codespace/STRL/BYOL/train.py", line 63, in main
    trainer.fit(model)
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 997, in fit
    results = self.dp_train(model)
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 270, in dp_train
    result = self.run_pretrain_routine(model)
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1185, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 343, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 303, in _reset_eval_dataloader
    num_batches = len(dataloader) if _has_len(dataloader) else float('inf')
  File "/home/jiangfan/miniconda3/envs/pytorch2/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 58, in _has_len
    raise ValueError('`Dataloader` returned 0 length.'
ValueError: `Dataloader` returned 0 length. Please make sure that your Dataloader at least returns 1 batch

**Comment by yichen928** [comment]
Hello. Please double-check the path of your dataset. In addition, make sure you have changed the configs in "BYOL/configs/config.yaml".

**Comment by xjiangfan** [comment]
> Hello. Please double-check the path of your dataset. In addition, make sure you have changed the configs in "BYOL/configs/config.yaml".

Hi, the path of datasets and the parameters of config.yaml is shown as follows. Is there any problem?
![image](https://user-images.githubusercontent.com/22809815/139614336-cbc8bf00-7a3c-4ef5-8c85-f27449a9215b.png)
![image](https://user-images.githubusercontent.com/22809815/139614555-a9d12951-1fd2-48ec-a439-7f2fcdadaa41.png)

**Comment by yichen928** [comment]
Have you changed the item "task" in "STRL/BYOL/config/config.yaml" to BYOL-dgcnn-cls? And this code is for pre-training, you should download the ShapeNet data as well.

**Comment by xjiangfan** [comment]
I'm sure my "STRL/BYOL/config/config.yaml" is ok for pre-training on ShapeNet, and ShapeNet dataset is also downloaded. In addition,  I think the problem is caused by "ModelNet40ClsContrast" when building a valuation dataloader. The figures show the pre-training dataloader is correctly created, but the evaluation dataloader is null. 

![pretrain_dataset](https://user-images.githubusercontent.com/22809815/139802507-cb060a71-73be-49fb-9e90-0b49753bc745.png)
![image](https://user-images.githubusercontent.com/22809815/139802883-47975e8f-a070-4113-a35c-289eed9f8d11.png)

So I want to know why the ModelNet40 evaluation dataloader is not created correctly. Note that ModelNet40 dataset is downloaded and put in the "modelnet40_normal_resampled_cache".

**Comment by yichen928** [comment]
It is very strange since this problem never happened in my device, and I also double-checked it just now. I advise you to check whether the file exists and not broken in this line. https://github.com/yichen928/STRL/blob/b7320d1b27cdb17f41a55b0349cb2eef6283bc8f/BYOL/data/ModelNet40Loader.py#L114

**Comment by xjiangfan** [comment]
The statement in the line 114 is fine and a "test" directory is created in the "modelnet40_normal_resampled_cache", but 'lmdb_env.stat()["entries"]' returned 0 in the line 116.
```
with lmdb.open(self._lmdb_file, map_size=1 << 36) as lmdb_env:
    self._len = lmdb_env.stat()["entries"]
```

![modelnet40](https://user-images.githubusercontent.com/22809815/140064907-3e75c709-db2e-4bd5-8034-6f50585f2b43.png)

**Comment by yichen928** [comment]
This line of code comes from this repo https://github.com/erikwijmans/Pointnet2_PyTorch/blob/acda965224f35854bc331cd5fe140393216b0a71/pointnet2/data/ModelNet40Loader.py#L110. 

I don't think this problem lies in the code of data loader, since it works well in many repos. It is more likely that you failed to download the data. You can try to re-download it from our given link: https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip

Make sure there are two sub-directories "train" and "test" in the unzipped data directory.

**Comment by xjiangfan** [comment]
I've solved this problem by re-downloading "modelnet40_normal_resampled.zip", and the directory "modelnet40_normal_resampled_cache" is auto-created by the codes. The key is don't create "modelnet40_normal_resampled_cache" by yourself. 

Last, Thanks a lot!

**Comment by xjiangfan** [comment]
I've solved this problem by re-downloading "modelnet40_normal_resampled.zip", and the directory "modelnet40_normal_resampled_cache" is auto-created by the codes. The key is don't create "modelnet40_normal_resampled_cache" by yourself. 

Last, Thanks a lot!
